#+TITLE: Lab 3. Speech synthesis

#+BEGIN_EXAMPLE
This version is preliminary and subject to change
#+END_EXAMPLE

In this lab session you will practice styling TTS output using Speech Synthesis Markup Language (SSML). It is assumed that you have read the relevant literature on the subject before attempting to solve the assignments.

For reference:
- Speech Synthesis Markup Language (SSML) Version 1.0, W3C Recommendation 7 September 2004, http://www.w3.org/TR/speech-synthesis/
- SSML support by ProphecyTTS: http://help.voxeo.com/go/help/xml.vxml.tts.ttsguide and the descriptions of SSML elements.
- SSML support by Amazon Polly: https://docs.aws.amazon.com/polly/latest/dg/ssml.html
- SSML support by Google: https://developers.google.com/actions/reference/ssml

You can use one of the TTS platforms:
1. ProphecyTTS (comes with Voxeo Prophecy)
2. [[https://aws.amazon.com/polly/][Amazon Polly]] (need to register)
3. [[https://cloud.google.com/text-to-speech/][Google Cloud TTS]] (need to register)

- for VG :: you will need to show extensive use of SSML tags, especially with regard to phonemes and prosody modification.

* Part A: SSML warm-up exercise
If you listen to the TTS output of the sentences:
#+BEGIN_EXAMPLE
The biggest loser among the top 10 cryptocurrencies is bitcoin cash (BCH), down 10.58 percent in the last 24 hours. It's also down 24.11 percent from the recent high of $1,641.40. 
#+END_EXAMPLE

it does not sound very good. Here is what seems wrong (depending on the platform, this is for ProphecyTTS):

- "cryptocurrencies" is pronounced incorrectly  
- 10.58 should be read as "ten point fifty-eight"
- The sentence overall sound is not very clear for a listener. Imagine hearing these kind of news on the radio, would you understand it?

Modify the sentence by adding some relevant SSML tags. Try to make use of all these tags: =<prosody>=, =<break>=, =<say-as>=, =<phoneme>= and =<emphasis>=.


* Part B: The sound of dialogue
The objective of this assignment is to "style" dialogue system's utterances. Here is what are going to work with:
#+BEGIN_SRC xml
I have your calendar open. 
<break strength="medium"/> 
For what date? 
<break strength="medium"/> 
What time would you like to start? 
<break strength="medium"/> 
How much time do you want to block out? 
<break strength="medium"/> 
What shall we call this? 
<break strength="medium"/> 
Ok. [create and style the appointment summary!]
#+END_SRC

Your job is to create the last utterance and to make all the system's utterances articulate better by inserting SSML tags in the dialogue.

* Part C: Speech Synthesis Poetry Slam
#+BEGIN_QUOTE
A poetry slam is a competition at which poets read or recite original work (or, more rarely, that of others). These performances are then judged on a numeric scale by previously selected members of the audience. (Wikipedia)
#+END_QUOTE
Your task in this assignment is to use SSML in order to get an artificial poet to recite the your favourite poem (just a couple of verses) with a speed and in "a style" similar to the way how it is read by an actor (or by a poet her/himself). 

You can refer to some poetry performance found on YouTube or elsewhere. And [[https://www.youtube.com/watch?v=IZYoGj8D8pY][listen to this]] for your text-to-speech inspiration.
